### ISSUE TITLE
Departure board in vue an electron

### ISSUE THREAD

**Issue by deg0nz** [joecorcoran/abfahrten.berlin#11]
Hey, I noticed, that you are building this via https://github.com/derhuerst/vbb-rest/issues/29.

We built a similar thing in February at a hackathon at my university.
It's an electron app written in vue instead of react. Maybe you can use stuff from us to make your life easier :) It is actually quite hacky and far from clean code (hackathon-style ;) ).

It is currently configured to show departues in S Wildau and Bhf. Königs Wusterhausen, but one can easily change the station IDs. We used Material Design, so it looks quite nice. Unfortunately, I have no Screenshot, but it should be easy to clone and run it.

You can find it here:
https://github.com/bstahl2005/vbb-monitor

You mentioned, that you're taking it slow because you never used React before. I've never used React either, but I can recommend vue: 
It seemed easy and fast to me to go through the vue docs and use it right away at the hackathon, where we had limited time. The learning curve wasn't too steep :)

I hope it helps :)
Greetings!

**Comment by joecorcoran** [comment]
Thanks for this! I'll check it out.
